# SLU12 - Linear Algebra & NumPy, Part 2

### Learning Notebook 2/2

*In this notebook we extend what we've learned about vectors to **Matrices**. We'll learn about special matrices, transpose, multiplication by a scalar and addition. We will then use NumPy arrays to represent matrices, perform matrix operations accessing rows and columns, learn about subsetting, boolean indexing and concatenation.*

---

**What's in this notebook**

3. [Matrices](#3.-Matrices)

  3.1 [Matrix definition](#3.1-Matrix-definition)  
  3.2 [Special matrices](#3.2-Special-matrices): square, diagonal, zero, identity, symmetric  
  3.3 [Matrix operations: multiplication by scalar and addition](#3.3-Matrix-operations:-multiplication-by-scalar-and-addition)  
  3.4 [Matrix transpose](#3.4-Matrix-transpose)


4. [NumPy arrays and matrices](#4.-NumPy-arrays-and-matrices)

  4.1 [Representing matrices with 2D arrays](#4.1-Representing-matrices-with-2D-arrays)  
  4.2 [Matrices and linear algebra using NumPy](#4.2-Matrices-and-linear-algebra-using-NumPy)  
  4.3 [Accessing rows and columns in 2D arrays](#4.3-Accessing-rows-and-columns-in-2D-arrays)  
  4.4 [Boolean indexing](#4.4-Boolean-indexing)  
  4.5 [Copying numpy arrays](#4.5-Copying-numpy-arrays)

---

### Imports

In [1]:
# numpy is the package we're going to learn about
# it is a widespread convention to import numpy using the alias np
# this convention makes your code more readable, so do use it
import numpy as np

# auxiliary stuff
import utils

On the first notebook, we learned about vectors, their main properties, basic operations and how we can apply all that using ndarrays and NumPy functionalities. Let's now dive into matrices, the most common way to store and represent data.

## 3. Matrices

If you read Learning Notebook 1 carefully, this section is going to be short and sweet, since it builds up on the algebraic operations we learned for vectors.

As a data scientist, you'll usually work with tables of data (a.k.a. datasets), where each column of data represents the observed values for a given variable (feature), and each row corresponds to a different observation (a combination of values of the different variables). Generally speaking, you can think of these tables as matrices, which could actually have different types of data (strings, numbers, etc.). In linear algebra, we're interested in dealing with numerical data, so let's focus on matrices of numbers.

### 3.1 Matrix definition

A matrix is *nothing more* than a table of numbers. Actually, we can also call a matrix a collection of **one or more** column vectors. For example, this is a matrix:

$$\mathbf{B} = 
    \begin{bmatrix} 
        1 & 2 & 0 & 1\\
        4 & 6 &-1 & 0\\
        -2& \sqrt{2} & 0 & -0.5\\
     \end{bmatrix}
$$

Each of the columns in $\mathbf{B}$ is a column vector. The first column vector in $\mathbf{B}$ is $\begin{bmatrix} 1 & 4 & -2\\\end{bmatrix}^T$ (remember the transpose?). Since we have 3 rows and 4 columns, we say that the **dimension** of the matrix is $3\times 4$ ("three by four"), or simply that "$\mathbf{B}$ is a $3\times 4$ matrix". Each number in the matrix is called an **entry**.

Now that you know this, the fact that there are "row vectors" and "column vectors" starts to make much more sense.

Also, notice that a row vector is nothing more than a $1\times n$ matrix, and a column vector is simply an $m\times 1$ matrix.

<div class="alert alert-block alert-info">
    A <b>matrix $\mathbf{A}$</b> of dimension $m\times n$ has $m$ rows and $n$ columns and is represented as:
    $$
    \mathbf{A} = 
    \begin{bmatrix}
        a_{1,1} & a_{1,2} & \cdots & a_{1,n}\\
        a_{2,1} & a_{2,2} & \cdots & a_{2,n}\\
        \vdots &\vdots & \ddots & \vdots\\
        a_{m,1} & a_{m,2} & \cdots & a_{m,n}\\
    \end{bmatrix}
    $$
</div>

Some observations:

- Each entry $a_{i,j}$ of the matrix $A$ has two indexes, the first corresponding to the row where it is located and the second to its column.

- In our first example above, $b_{2,3} = -1$. Do not confuse indexing in mathematical notation (starts at $1$) with indexing in Python (starts at $0$).

**Equality of matrices**: two matrices $\mathbf{A}$ and $\mathbf{B}$ are equal **if and only if** they have the **same size ($m\times n$) and $a_{i,j} = b_{i,j}$, for every $i, j$**.

### 3.2 Special matrices

*All matrices are special... but some are "squarer".* 🔲

#### 3.2.1 Square matrix

When we have a matrix with the **same number of rows and columns ($m=n$)**, we call it a **square matrix**.

#### 3.2.2 Diagonal matrix

The **diagonal matrix** is a **square** matrix where all the elements **outside** its **main diagonal** are zero:

$$
A = 
\begin{bmatrix}
    a_{1,1} & 0 & \cdots & 0\\
    0 & a_{2,2} & \cdots & 0\\
    \vdots &\vdots & \ddots & \vdots\\
    0 & 0 & \cdots & a_{n,n}\\
\end{bmatrix}
$$

<div class="alert alert-block alert-info">
    A square matrix $\mathbf{A}$ is said to be <b>diagonal</b> if $a_{ij} = 0,\;\; i\neq j$.
</div>

**Note that** this does not mean that the elements of the diagonal cannot be zero

#### 3.2.3 Zero matrix

The **zero matrix** is a matrix where all entries are equal to zero:

$$
\mathbf{O} = 
\begin{bmatrix}
    0 & 0 & \cdots & 0\\
    0 & 0 & \cdots & 0\\
    \vdots &\vdots & \ddots & \vdots\\
    0 & 0 & \cdots & 0\\
\end{bmatrix}
$$

<div class="alert alert-block alert-info">
    The <b>zero matrix</b> $\mathbf{O}$ is a matrix where all entries are zeros, $o_{i,j} = 0$.
</div>

#### 3.2.4 Identity matrix

The **identity matrix** is a **diagonal** matrix (and therefore also a **square** matrix) where all the elements in the main diagonal are ones:

$$
I_n = 
\begin{bmatrix}
    1 & 0 & \cdots & 0\\
    0 & 1 & \cdots & 0\\
    \vdots &\vdots & \ddots & \vdots\\
    0 & 0 & \cdots & 1\\
\end{bmatrix}
$$

The **identity matrix** is a different kind of special. Multiplying any matrix by the identity results in the matrix itself (we'll study matrix multiplication in SLU13).

<div class="alert alert-block alert-info">
    The <b>identity matrix</b> is a diagonal matrix of size $n\times n$ where the entries in the main diagonal are all ones and all the elements out of the main diagonal are zeros: $a_{i,j} = 1$, for $i = j$ and $a_{i,j} = 0$, for $i\neq j$. It is usually denoted as $\mathbf{I_n}$.
</div>

#### 3.2.5 Symmetric matrix

A square matrix $\mathbf{A}$  is symmetric when all its entries are symmetric relative to its main diagonal. For example:

$$
\begin{bmatrix}
    1 & 2 & 3\\
    2 & 0 & \sqrt{2}\\
    3 & \sqrt{2} & -1
\end{bmatrix}
$$

If you look at the elements outside the diagonal, you'll notice a symmetry in relation to the diagonal of the matrix. The element $a_{2,1}$ is equal to the element $a_{1,2}$, the element $a_{3,1}$ is equal to entry $a_{1,3}$ and the element $a_{3,2}$ is equal to element $a_{2,3}$.

<div class="alert alert-block alert-info">
    A <b>symmetric matrix</b> $\mathbf{A}$ is a square matrix where the equality $a_{i,j} = a_{j,i}$ holds true for any entry in the matrix.
</div>

Notice that row and column indexes are always equal for **each entry** in the diagonal ($a_{1,1}$, $a_{2,2}$,... $a_{m,m}$), in a square matrix.

---

There are a few other special matrices. For example, the **lower triangular** is a square matrix where all the entries **above** the main diagonal are **zero**, and the **upper triangular** is a square matrix where all the entries **below** the main diagonal are **zero**. [check here](https://www.youtube.com/watch?v=H5ZE3I3rLSY)

---

<img src="./media/nothing_identity.png"/>

---

### 3.3 Matrix operations: multiplication by scalar and addition

#### 3.3.1 Multiplying a matrix by a scalar

This is pretty much the same thing as we did with vectors.

Let's check one example:

$$
2\cdot
\begin{bmatrix}
    0 & 1 & 0\\
    -1 & 0.5 & 2
\end{bmatrix}
=
\begin{bmatrix}
    2\times 0 & 2\times 1 & 2\times 0\\
    2\times (-1) & 2\times 0.5 & 2\times 2
\end{bmatrix}
=
\begin{bmatrix}
    0 & 2 & 0\\
    -2 & 1 & 4
\end{bmatrix}
$$

#### 3.3.2 Addition and subtraction

Remember that you can only add or subtract two vectors with the same dimension? In the case of matrices, they need to have the same number of rows **and** the same number of columns, this is, they need to be the **same size**:

Let's add matrices $\mathbf{A} = \begin{bmatrix}1&-1\\0&2\\-0.5&1\end{bmatrix}$ and $\mathbf{B} = \begin{bmatrix}0.2&-2\\-3&1\\5&2\end{bmatrix}$.


$
\mathbf{A}
+
\mathbf{B} =
\begin{bmatrix}
    1 + 0.2 & -1 + (-2)\\
    0 + (-3) & 2 + 1\\
    -0.5 + 5 & 1 + 2
\end{bmatrix} =
\begin{bmatrix}
    1.2 & -3\\
    -3 & 3\\
    4.5 & 3
\end{bmatrix}
$


**Notice that** you can also think of the operation above has having added:
- the first column vector in $\mathbf{A}$ with the first column vector in $\mathbf{B}$
- the second column vector in $\mathbf{A}$ with the second column vector in $\mathbf{B}$

So, we basically performed two separate additions between vectors at once, inside a matrix. Interesting, right?

#### 3.3.3 Properties of matrix addition and multiplication by scalars

Similarly to vectors, we have the following properties:

$\;\;\text{1. }\;\; \mathbf{A} + \mathbf{B} = \mathbf{B} + \mathbf{A}\;\;$ (**commutativity**)

$\;\;\text{2. }\;\; \mathbf{A} + \mathbf{O} = \mathbf{A}$

$\;\;\text{3. }\;\; c\left(\mathbf{A} + \mathbf{B}\right) = c\mathbf{A} + c\mathbf{B},\hspace{.2cm} c\in \mathbb{R}$ (**distributivity of a scalar**)

$\;\;\text{4. }\;\; \left(cd\right)\mathbf{A} = c\left(d\mathbf{A}\right)$

$\;\;\text{5. }\;\; \mathbf{A} + (\mathbf{B} + \mathbf{C}) = (\mathbf{A} + \mathbf{B}) + \mathbf{C}\;\;$ (**associativity**)

$\;\;\text{6. }\;\; \mathbf{A} + (-\mathbf{A}) = \mathbf{O}$

$\;\;\text{7. }\;\; (c + d) \mathbf{A} = c \mathbf{A} + d \mathbf{A}$

where $\mathbf{O}$ is the zero matrix, and $c$ and $d$ are scalars.

Once more, do not worry about knowing all of these properties by heart. As you start practicing operations with matrices, this will become second nature.

> 📝 **Pen and paper exercise 8**: Which special matrix or matrices results from the following operation?
> 
> $$\begin{bmatrix}
    -1 & 2\\
    4 & 0.5
    \end{bmatrix}
    - 0.5
    \begin{bmatrix}
    -2 & 4\\
    8 & 1
    \end{bmatrix}
    $$

### 3.4 Matrix transpose

Remember the transpose of a row vector is a column vector, and vice-versa?... The logic is the same here. Rows become columns, columns become rows.

$$
\mathbf{A}^T
=
\begin{bmatrix}
    0 & 1 & 0\\
    -1 & 0.5 & 2
\end{bmatrix}^T
=
\begin{bmatrix}
    0 & -1\\
    1 & 0.5\\
    0 & 2
\end{bmatrix}
$$

Matrix $A$ is of size $2\times 3$, and its transpose, $\mathbf{A}^T$, is of size $3\times 2$. The 3 vector columns were transposed to 3 row vectors, by order.

#### 3.4.1 Matrix transpose laws

Let's check some of the properties of the matrix transpose:

$\;\;\text{1. }\;\; (\mathbf{A}+\mathbf{B})^T = \mathbf{A}^T+\mathbf{B}^T$

$\;\;\text{2. }\;\ (c\mathbf{A})^T = c\mathbf{A}^T$

$\;\;\text{3. }\;\; \mathbf{A}$ is symmetric if and only if $\mathbf{\mathbf{A}} = \mathbf{A}^T$.

> 📝 **Pen and paper exercise 9**: Check that the matrix below satisfies property 3:
> 
> $$\begin{bmatrix}
     1 & 0 & 2\\
     0 & 1 & 3\\
     2 & 3 & 2
    \end{bmatrix}
    $$

> 📝 **Pen and paper exercise 10**: Calculate $(\mathbf{A}+\mathbf{B})^T$ and $\mathbf{A}^T+\mathbf{B}^T$ and check that they result in the same output matrix (property 1), using the matrices
> $
A = 
\begin{bmatrix}
    1 & 2\\
    -3& 5
\end{bmatrix}
  $
> and $
B = 
\begin{bmatrix}
    0 & 1\\
    4 & -6
\end{bmatrix}
  $.

---

That's enough linear algebra for now. Next week, on SLU13, we'll learn more about useful things we can do with matrices and vectors.

Let's proceed to the last section of this notebook, where we perform matrix operations with NumPy, and learn more about indexing and subsetting ndarrays.

<img src="./media/almost.gif"/>

---

## 4. NumPy arrays and matrices

### 4.1 Representing matrices with 2D arrays

Let's bring back the arrays!! 💻🐍

In [2]:
# a 2x3 matrix
A = np.array([
    [2, 0.1, -1],
    [3, 1/5, np.sqrt(2)]  # np.sqrt(2) is the square root of 2; np.sqrt() can also be used for arrays
])

# a 2x3 matrix
B = np.array([[-2, -2, 1],
              [0, 1, 1]])

# show our matrices
print("A\n:", A, "\n")
print("B\n:", B)

A
: [[ 2.          0.1        -1.        ]
 [ 3.          0.2         1.41421356]] 

B
: [[-2 -2  1]
 [ 0  1  1]]


In [3]:
# print shape and number of dimensions of array A
print("A.shape:", A.shape)
print("A.ndim:", A.ndim)

# print shape and number of dimensions of array B
print("B.shape:", B.shape)
print("B.ndim:", B.ndim)

A.shape: (2, 3)
A.ndim: 2
B.shape: (2, 3)
B.ndim: 2


**Arrays shape and dimension**:

- The **shape** of array `A` is `(2, 3)`... hmmm, that's the dimension of the matrix $A$, $2\times 3$!
- The **number of array dimensions** of `A` is `2` (we have 1 axis for the rows and another for the columns).

### 4.2 Matrices and linear algebra using NumPy

Let's apply what we learned about matrices in section 3, using NumPy.

#### 4.2.1 Special matrices

**Zero matrix**

In [4]:
# a zero matrix of size 4x2
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

**Identity matrix**

In [5]:
# identity matrix of size 5x5 (also is square & diagonal),
# represented by an array (shape = (5, 5))
I = np.identity(5)  # the input is the number of rows (or columns)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 4.2.2 Matrix operations

**Multiplication by a scalar**

Let's bring back our matrix `B`:

In [6]:
print("Matrix B:")
print(B)

Matrix B:
[[-2 -2  1]
 [ 0  1  1]]


To multiply a matrix (2D array) by a scalar, we simply use the Python multiplication operator `*`:

In [7]:
0.5 * B  # simply use the Python multiplication operator *

array([[-1. , -1. ,  0.5],
       [ 0. ,  0.5,  0.5]])

**Addition (and subtraction) of matrices**

Let's bring back our matrices `A` and `B`:

In [8]:
print("Matrix A:\n", A, "\n")
print("Matrix B:\n", B)

Matrix A:
 [[ 2.          0.1        -1.        ]
 [ 3.          0.2         1.41421356]] 

Matrix B:
 [[-2 -2  1]
 [ 0  1  1]]


To add two matrices (2D arrays) together, we can use Python addition operator `+`, which adds the matrices element-wise:

In [9]:
A + B  # simply use the Python addition operator +

array([[ 0.        , -1.9       ,  0.        ],
       [ 3.        ,  1.2       ,  2.41421356]])

We can do the same for subtraction, using `-`:

In [10]:
A - B  # simply use the Python subtraction operator -

array([[ 4.        ,  2.1       , -2.        ],
       [ 3.        , -0.8       ,  0.41421356]])

**Properties of matrix addition and multiplication by scalars**

Let's now check some properties we've learned using NumPy. For this we will use the function [`numpy.array_equal()`](https://numpy.org/doc/1.20/reference/generated/numpy.array_equal.html), which allows to compare two arrays for both shape and elements equality, instead of only element-wise.

In [11]:
# create one more matrix to play with
C = np.array([[-2, 1, -1],
              [-2, 1, 1]])

In [12]:
# print our matrices
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix C:\n", C)

Matrix A:
 [[ 2.          0.1        -1.        ]
 [ 3.          0.2         1.41421356]]
Matrix B:
 [[-2 -2  1]
 [ 0  1  1]]
Matrix C:
 [[-2  1 -1]
 [-2  1  1]]


**Distributivity of a scalar when adding two matrices:** $c (\mathbf{A} + \mathbf{B}) = c \mathbf{A} + c\mathbf{B}$

In [13]:
c = 2  # a scalar
np.array_equal(c * (A + B), (c * A) + (c * B))

True

Notice that using the `==` operator will compare the entries element-wise, and not the entire arrays at once:

In [14]:
c * (A + B) == (c * A) + (c * B)

array([[ True,  True,  True],
       [ True,  True,  True]])

**Associativity of matrix addition:** $\mathbf{A} + (\mathbf{B} + \mathbf{C}) = (\mathbf{A} + \mathbf{B}) + \mathbf{C}$

In [15]:
np.array_equal(A + (B + C), (A + B) + C)

False

Wait, what?? Is linear algebra wrong??...

Never! ;)

In [16]:
A + (B + C)

array([[-2.        , -0.9       , -1.        ],
       [ 1.        ,  2.2       ,  3.41421356]])

In [17]:
(A + B) + C

array([[-2.        , -0.9       , -1.        ],
       [ 1.        ,  2.2       ,  3.41421356]])

Both sides of the equality look the same, right?

The problem is that, under the hood, NumPy is making some approximations on the value of the last element (computers don't have infinite memory to save all the decimal cases we need!). Let's first round all the elements to a lower number of decimal cases, using [`.round()`](https://numpy.org/doc/1.20/reference/generated/numpy.ndarray.round.html), prior to the comparison made by `numpy.array_equal`. This way we ensure we are comparing only up to a certain number of decimal cases.

Let's check if this works:

In [18]:
np.array_equal((A + (B + C)).round(2), 
               ((A + B) + C).round(2))

True

Ahh... normality restored.

#### 4.2.3 Transpose

Because we represent matrices by 2D arrays (and not 1D arrays), we can use the attribute `.T` directly:

In [19]:
print("Matrix A:\n", A)

Matrix A:
 [[ 2.          0.1        -1.        ]
 [ 3.          0.2         1.41421356]]


In [20]:
A_T = np.transpose(A)  # same as A.T
A_T

array([[ 2.        ,  3.        ],
       [ 0.1       ,  0.2       ],
       [-1.        ,  1.41421356]])

### 4.3 Accessing rows and columns in 2D arrays

Remember learning how to index lists and lists of lists, slice pieces of lists and concatenate them together? Let's see how we can do this with 2D arrays.

#### 4.3.1 Indexing

In [21]:
# 3x2 matrix represented as a list
a_list = [[1, 2], [3, 4], [5, 6]]

# the same 3x2 matrix represented by an array
a_array = np.array([[1, 2], [3, 4], [5, 6]])

In [22]:
a_list

[[1, 2], [3, 4], [5, 6]]

In [23]:
a_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
a_array.shape

(3, 2)

**Select a single row**

In [25]:
a_list[0]  # access first list (first row)

[1, 2]

In [26]:
a_array[0]  # access first axis (first row)

array([1, 2])

**Select a single element**

a) using `[][]`

Let's select the entry $a_{2,1}$ in our matrix (remember that in mathematical notation indexing starts at 1).

In [27]:
a_list[1][0]  # access first element of the second row (list)

3

In [28]:
a_array[1][0]  # access first element of the second row (numpy array) -- access rows on 1st axis, columns on 2nd axis

3

b) using `[,]`

The `ndarray` also supports another type of indexing, where we have one index per axis separated by commas (tuple):

In [29]:
a_array[1, 0]

3

Notice that the same is not possible for Python lists:

In [30]:
try:  
    a_list[1, 0]
except Exception as e: 
    print("TypeError:", e)

TypeError: list indices must be integers or slices, not tuple


#### 4.3.2 Subsetting rows and columns

Let's create a matrix called `b_array` below. We'll use [`numpy.arange()`](https://numpy.org/doc/1.20/reference/generated/numpy.arange.html), which allows us to create an array of evenly spaced values (just like we did before in the course, using `range()` and lists).

In [31]:
b_array = np.arange(0, 5*5).reshape(5, 5)  # (5x5) matrix with integer values from 0 to 24
b_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Let's check the examples below of how we can subset rows and columns in 2D arrays:

In [32]:
b_array[3:]  # access rows starting at the fourth row

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
b_array[1:, 1]  # access second row and beyond, access second column

array([ 6, 11, 16, 21])

Notice that the array now looks like a row, although in the initial matrix this piece of data belongs to the same column. Be careful how you interpret output dimensions when subsetting arrays.

Remember learning how to slice lists? It went something like:

```Python
a_list[start:stop:step]
```

We can apply the same principle to arrays, in each of the axis:

In [34]:
b_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
b_array[
    1:4,  # 1st axis: access rows from the second (index 1) until the fourth (index 3)
    :-1  # 2nd axis: access all columns until last one (excluded)
]  

array([[ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

One more:

In [36]:
b_array[
    2:8:2, # 1st axis: access rows starting at 3rd row (index 2), and each 2nd row after that
    3: # 2nd axis: access from the 4th column until the last
]  

array([[13, 14],
       [23, 24]])

#### 4.3.3 Concatenation

We can concatenate numpy arrays along rows or columns, if their dimensions are compatible:

In [37]:
# create arrays of shape (2, 3)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]


In [38]:
np.concatenate((A, B), axis = 0)  # concatenate along axis 0 (rows)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
np.concatenate((A, B), axis = 1)  # concatenate along axis 1 (columns)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### 4.3.4 Iterating through arrays

You can iterate through the rows of a matrix (2D array):

In [40]:
a = np.array([[.0, .2, .4], [.6, .8, 1.]])
i = 1
for row in a:
    print(f"row {i}: {row}")
    i+=1

row 1: [0.  0.2 0.4]
row 2: [0.6 0.8 1. ]


### 4.4 Boolean indexing

This is the last topic on this notebook, but don't rush it, it's a very useful one.

Instead of explicitly telling NumPy which indexes you want to access in an array, you might wish to select parts of an array based on a condition. For that you can use a boolean expression.

For example, consider the following 2D array representing a matrix of size $2\times 3$:

In [41]:
a = np.array([[-1, -.5, 0.2],
              [.5, 1, 1.5]])
a.shape

(2, 3)

Let's say I want to **filter** (keep only) the entries **where the condition $a_{i,j} > 0$ is met**. You can do it in the following manner:

In [42]:
a_positives = a[a > 0]
a_positives

array([0.2, 0.5, 1. , 1.5])

In [43]:
a > 0 # this is the boolean mask we used above

array([[False, False,  True],
       [ True,  True,  True]])

In [44]:
a_positives.shape

(4,)

❗ Notice the output is a 1D array with the elements that meet the condition `> 0`, it no longer has the shape and dimension of `a`.

Also, the expression ``a>0`` is itself an array, more specifically, a **boolean array** or **boolean mask**, where the elements are `True` where the condition holds and `False` otherwise:

In [45]:
a_bool = a > 0
a_bool

array([[False, False,  True],
       [ True,  True,  True]])

Using `.dtype` we can confirm the type of this array:

In [46]:
a_bool.dtype

dtype('bool')

Can you use the mask above on another array?... Yes!

In [47]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])
b[a_bool]

array([2, 3, 4, 5])

Note that this **won't** filter by the positive values in `b` (which would be all the elements above zero), but instead by the corresponding positions where values in `a` were positive.

What happens if we use `a_bool` with an array of different shape?

In [48]:
# 2D array representing a 2x4 matrix
c = np.array([[0, 1, 2, 6],
              [3, 4, 5, 7]])

# you learned about exceptions in SLU11!! ;)
try:
    c[a_bool]
except Exception as e: 
    print("IndexError:", e)

IndexError: boolean index did not match indexed array along dimension 1; dimension is 4 but corresponding boolean dimension is 3


**The `~` operator**

Consider the following array:

In [49]:
d = np.array([[-1, -2, -3, -4], 
              [1, 2, 3, 4]])
d

array([[-1, -2, -3, -4],
       [ 1,  2,  3,  4]])

We could create a mask to filter all elements that are bigger than zero:

In [50]:
d > 0

array([[False, False, False, False],
       [ True,  True,  True,  True]])

To create the reverse mask, this is, a mask where the condition `d > 0` is **not** true, we can use the negation operator, `~`:

In [51]:
~(d > 0)

array([[ True,  True,  True,  True],
       [False, False, False, False]])

Note that `~(d > 0)` is the same as `d <= 0`:

In [52]:
d <= 0

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [53]:
print("d[d>0] = ", d[d>0])

d[d>0] =  [1 2 3 4]


In [54]:
print("d[~(d>0)] = ", d[~(d>0)])

d[~(d>0)] =  [-1 -2 -3 -4]


In [55]:
print("d[d<=0] = ", d[d<=0])

d[d<=0] =  [-1 -2 -3 -4]


### 4.5 Copying numpy arrays

Just like you learned in past SLUs for other data structures, you should use the `.copy()` method when you want to copy arrays:

**Correct way:**

```Python
a = np.array([[1], [2]])
b = a.copy()  # GOOD PRACTICE
```

**Wrong way:**

```Python
a = np.array([[1], [2]])
b = a  # BAD PRACTICE
```

---

## Wrapping up

What we've learned so far:
- what are vectors, their properties, linear combinations and linear independence;
- what are matrices, special matrices, transpose, adding matrices and multiplying by scalars;
- how to use NumPy to create and manipulate 1D and 2D arrays, and perform basic linear algebra operations on vectors and matrices;
- indexing NumPy arrays.

---



At this moment, you might still be asking yourself how all these vector and matrix operations will actually translate into real problems in data science. Worry not. It's all going to become clear pretty soon, as we dive into matrix multiplication and systems of linear equations.

The good thing is that, if you took your time with Learning Notebooks 1 and 2, you know all you need to know to understand the concepts in SLU13.

Maths is just like neurons... *Use it or lose it.* So **go go go to the Exercise Notebook**!!

---

### Resources on Linear Algebra:

- [**3Blue1Brown**](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab);

- [**YouTube Playlist for MIT 18.06SC Linear Algebra, Fall 2011**](https://www.youtube.com/watch?v=7UJ4CFRGd-U&list=PL221E2BBF13BECF6C).


### Resources on NumPy:

* [**NumPy v1.20.0 Quickstart tutorial**](https://numpy.org/doc/1.20/user/quickstart.html);

* [**Python Numpy @ GeeksforGeeks**](https://www.geeksforgeeks.org/python-numpy/);

* [**Slicing and Advanced Indexing @ GeeksforGeeks**](https://www.geeksforgeeks.org/indexing-in-numpy/);

* [**Integer and Boolean Indexing @ TutorialsPoint**](https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm).

---

<img src="./media/enough_is_enough.gif"/>

---